[package]
name = "ssb-multiformats"
version = "0.1.0"
authors = ["AljoschaMeyer <mail@aljoscha-meyer.de>"]
edition = "2018"
license = "AGPL-3.0"

[dependencies]
base64 = "0.10.0"
serde = "1.0.80"
ssb-crypto = { version = "0.1.3", path = "../ssb-crypto" }

[dev-dependencies]
matches = "0.1.8"
